apiVersion: apps/v1
kind: Deployment
metadata:
  name: drug-catalog-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drug-catalog-service
  template:
    metadata:
      labels:
        app: drug-catalog-service
    spec:
      serviceAccountName: drug-catalog-service
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      containers:
        - name: drug-catalog-service
          image: 873135413040.dkr.ecr.us-east-1.amazonaws.com/drug-catalog-service:sha-a0017b8
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          envFrom:
            - configMapRef:
                name: drug-catalog-service
            - secretRef:
                name: db-credentials
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
